[package]
name = "bzr-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.bzr]
path = ".."
default-features = false

[[bin]]
name = "fuzz_xmlrpc_parse"
path = "fuzz_targets/fuzz_xmlrpc_parse.rs"
test = false
doc = false
bench = false
